# Site Settings
title: ivim's blog
email: admin@ivim.vip
description: >
  admin@ivim.vip's blog with GitHub.
baseurl: "/xxx"
url: "http://www.ivim.vip"
twitter_username: 
github_username:  jinzhisu
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
